services:
  chat-ui:
    image: ghcr.io/huggingface/chat-ui:sha-f0ce7fc
    container_name: webui-station
    volumes:
      - data:/data
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat-ui.rule=Host(`chat-ui.docker.local`)"
      - "traefik.http.routers.chat-ui.entrypoints=websecure"
      - "traefik.http.routers.chat-ui.tls=true"
      - "traefik.http.services.chat-ui.loadbalancer.server.port=3000"
    networks:
      - network_service
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - MONGODB_URL=mongodb://shared:shared@10.10.3.20
      - MONGODB_DB_NAME=chat-ui
      - OPENAI_BASE_URL=http://10.10.3.32:11434/v1
      - OPENAI_API_KEY=ollama
      - MCP_FORWARD_HF_USER_TOKEN=true
      - MCP_SERVERS=[{"name":"Postgres Cookery","url":"https://mcp-cookery.docker.local/sse"}]

networks:
  network_service:
    external: true

volumes:
  data: