services:
  base:
    build:
      context: base
    image: ubuntu:local

  docker:
    build:
      context: docker
    image: ubuntu:docker
    depends_on:
      - base

  go-lang:
    build:
      context: go-lang
    image: ubuntu:golang
    depends_on:
      - docker

  misc:
    build:
      context: misc
    image: ubuntu:misc
    depends_on:
      - go-lang
