services:
  base:
    build:
      context: base
    image: ubuntu:local

  docker:
    build:
      context: docker
    image: ubuntu:docker
    depends_on:
      - misc

  misc:
    build:
      context: misc
      target: misc
    image: ubuntu:misc
    depends_on:
      - base

  tool:
    build:
      context: misc
      target: tool
    image: ubuntu:tool
    depends_on:
      - misc
