services:
  fluent-bit:
    image: fluent/fluent-bit:4.1
    container_name: fluent-bit
    restart: unless-stopped
    networks:
      - network_service
    volumes:
      - /var/log:/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - ./parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro

networks:
  network_service:
    external: true
