[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020
    Health_Check   On

    Parsers_File /fluent-bit/etc/parsers.conf

# Syslog
[INPUT]
    Name            tail
    Path            /var/log/syslog
    Tag             host.syslog
    Refresh_Interval 5

# CPU
[INPUT]
    Name            cpu
    Tag             host.cpu
    Interval_Sec    5

# Mem
[INPUT]
    Name            mem
    Tag             host.mem
    Interval_Sec    5

# Swap
[INPUT]
    Name            mem
    Tag             host.swap
    Interval_Sec    30

# Disk IO
[INPUT]
    Name            disk
    Tag             host.disk
    Interval_Sec    60

# Net
# [INPUT]
#     Name            netif
#     Tag             host.net
#     Interface       eth0
#     Interval_Sec    5

# Docker Logs
[INPUT]
    Name             tail
    Path             /var/lib/docker/containers/*/*.log
    Parser           docker
    Tag              docker.*
    Tag_Regex        (?<container_id>[^/]+)-json\.log$
    Refresh_Interval 10
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

# Filter Docker Logs
[FILTER]
    Name         parser
    Match        docker.*
    Key_Name     log
    Parser       json_log
    Reserve_Data True

# [FILTER]
#     Name    lua
#     Match   docker.*
#     script  container_name.lua
#     call    simplify_container_metadata
# , container_id=$container_id_short
# - ./container_name.lua:/fluent-bit/etc/container_name.lua:ro

# Loki - Host Metrics
[OUTPUT]
    Name        loki
    Match       host.*
    Host        loki.docker.local
    Port        3100
    Labels      job=fluentbit,source=host
    Auto_Kubernetes_Labels Off

# Loki - Docker Logs
[OUTPUT]
    Name      loki
    Match     docker.*
    Host      loki.docker.local
    Port      3100
    Labels    job=fluentbit,source=docker
    Auto_Kubernetes_Labels Off