services:
  checkpoint:
    image: offen/docker-volume-backup:v2
    container_name: checkpoint
    restart: always
    environment:
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-}
      AWS_ENDPOINT_PROTO: ${AWS_ENDPOINT_PROTO:-}
      AWS_ENDPOINT: ${AWS_ENDPOINT:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}

      TZ: ${TZ:-UTC}

      BACKUP_SOURCES: /backup
      BACKUP_FILENAME: checkpoint_%Y%m%d_%H%M%S.tar.gz
      BACKUP_CRON_EXPRESSION: "0 3 * * *" # Everyday at 3:00 AM
      BACKUP_RETENTION_DAYS: 15
    networks:
      - network_security
    volumes:
      - gitea_data:/backup/gitea:ro
      - postgresql_shared:/backup/postgres_shared:ro
      
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Alternative to mounting individual volumes, but may include more data than desired.
      # - /var/lib/docker/volumes:/backup:ro 
    dns:
      - 10.10.5.200

volumes:
  gitea_data:
    external: true
  postgresql_shared:
    external: true

networks:
  network_security:
    external: true