services:
  checkpoint:
    image: offen/docker-volume-backup:v2
    container_name: checkpoint
    restart: always
    environment:
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME:-}
      AWS_ENDPOINT_PROTO: ${AWS_ENDPOINT_PROTO:-}
      AWS_ENDPOINT: ${AWS_ENDPOINT:-}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}

      TZ: ${TZ:-UTC}

      BACKUP_SOURCES: /backup
      BACKUP_FILENAME: checkpoint_%Y%m%d_%H%M%S.tar.gz
      BACKUP_CRON_EXPRESSION: "0 3 * * *" # Everyday at 3:00 AM
      BACKUP_RETENTION_DAYS: 15
    networks:
      - network_security
    volumes:
      - /var/lib/docker/volumes:/backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    dns:
      - 10.10.5.200

networks:
  network_security:
    external: true