services:
  pihole:
    container_name: dns_pihole
    image: pihole/pihole:2025.07.1
    environment:
      TZ: ${TZ}
      FTLCONF_webserver_api_password: ${API_PSWD}
      FTLCONF_dns_upstreams: "10.10.5.201" # Unbound
      FTLCONF_dns_listeningMode: "all"
      SKIPGRAVITYONBOOT: true
    volumes:
      - data:/etc/pihole/
      - dnsmasq:/etc/dnsmasq.d/
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

    # Expose DNS and DHCP ports to the host
    ports:
      - 53:53
      - 53:53/udp
      - 67:67/udp

    networks:
      network_security:
        ipv4_address: 10.10.5.200 # :53/tcp/udp :67/udp :443/tcp :80/tcp
      network_user:
        ipv4_address: 10.10.4.200
      network_service:
        ipv4_address: 10.10.3.200

    # traefik labels for reverse proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pi.docker.local`)"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.docker.network=network_service"

networks:
  network_security:
    external: true
  network_service:
    external: true
  network_user:
    external: true

volumes:
  data:
    external: false
  dnsmasq:
    external: false
