services:
  chartdb:
    image: ghcr.io/chartdb/chartdb:1.19.0
    container_name: chartdb
    environment:
      - OPENAI_API_ENDPOINT=https://chartdb.docker.local/v1
      # - LLM_MODEL_NAME=Qwen/Qwen2.5-32B-Instruct-AWQ
      - DISABLE_ANALYTICS=true
    restart: unless-stopped
    networks:
      - network_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chartdb.rule=Host(`chartdb.docker.local`)"
      - "traefik.http.routers.chartdb.entrypoints=websecure"
      - "traefik.http.routers.chartdb.tls=true"
      - "traefik.http.services.chartdb.loadbalancer.server.port=80"
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "10m"
    #     max-file: "3"

networks:
  network_service:
    external: true