services:
  squid:
    image: ubuntu/squid:5.2-22.04_beta
    container_name: squid
    restart: always
    ports:
      - 3128:3128
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - data:/var/spool/squid
    environment:
      - TZ=${TZ}
    networks:
      - network_service

volumes:
  data:


networks:
  network_service:
    external: true
