services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    restart: always
    networks:
      network_service:
        ipv4_address: 10.10.3.22
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=admin
      - WOODPECKER_AGENT_SECRET=${AGENT_SECRET}

      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://gitea.docker.local
      - WOODPECKER_GITEA_CLIENT=${GITEA_CLIENT}
      - WOODPECKER_GITEA_SECRET=${GITEA_SECRET}

      - WOODPECKER_HOST=http://woodpecker.docker.local
      - WOODPECKER_GRPC_ADDR=0.0.0.0:9000
      - WOODPECKER_SERVER_ADDR=0.0.0.0:8000

      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite3
    volumes:
      - data:/var/lib/woodpecker
    dns:
      - 10.10.3.200
    
    # traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.woodpecker.rule=Host(`woodpecker.docker.local`)"
      - "traefik.http.routers.woodpecker.entrypoints=web"
      - "traefik.http.services.woodpecker.loadbalancer.server.port=8000"

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=10.10.3.22:9000
      - WOODPECKER_AGENT_SECRET=supersecret123
      - WOODPECKER_MAX_WORKFLOWS=2
      - WOODPECKER_BACKEND_DOCKER_NETWORK=network_service
    networks:
      network_service:
        ipv4_address: 10.10.3.23
    dns:
      - 10.10.3.200

volumes:
  data:

networks:
  network_service:
    external: true