services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rstudio:lidr
    container_name: rstudio
    environment:
      PASSWORD: ${PASSWORD:-}
      DISABLE_AUTH: true
    volumes:
      - data:/home/rstudio
      - workspace_data:/home/rstudio/workspace

    networks:
      - network_service

     # traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio.rule=Host(`rstudio.cs`)"
      - "traefik.http.routers.rstudio.entrypoints=websecure"
      - "traefik.http.routers.rstudio.tls=true"
      - "traefik.http.routers.rstudio.tls.certresolver=step-ca-resolver"
      - "traefik.http.services.rstudio.loadbalancer.server.port=8787"

networks:
  network_service:
    external: true

volumes:
  data:
    external: false
  workspace_data:
    external: true