# -----------------------------------------------------------------------------
# Script: Generate-SSHConfig.ps1
# Engine by Geltdro - 04/01/2026
# -----------------------------------------------------------------------------

$ConfigPath = "$HOME\.ssh\config"

# 1. Single Responsibility: El modelo de datos (Source of Truth)
$Inventory = @(
    @{
        Host         = "hp22b"
        HostName     = "192.168.1.250"
        User         = "luist"
        IdentityFile = "~/.ssh/id_ecdsa"
        Params       = @("ForwardAgent yes", "IdentitiesOnly yes")
    },
    @{
        Host         = "geltdro-proxy"
        HostName     = "geltdro.docker.local"
        User         = "geltdro"
        IdentityFile = "~/.ssh/id_tool"
        Params       = @("ForwardAgent yes", "ProxyCommand ncat --ssl %h %p", "IdentitiesOnly yes")
    }
)

# 2. Interface Segregation & Dependency Inversion: El formateador es puro
function Get-SSHHostBlock {
    param ([hashtable]$Node)

    $Lines = @("Host $($Node.Host)")
    $Lines += "    HostName $($Node.HostName)"
    $Lines += "    User $($Node.User)"

    if ($Node.IdentityFile) { $Lines += "    IdentityFile $($Node.IdentityFile)" }

    # Manejo dinámico de parámetros extra
    foreach ($P in $Node.Params) { $Lines += "    $P" }

    return ($Lines -join "`n") + "`n"
}

# 3. Execution: El orquestador
function Update-SSHConfig {
    try {
        $Header = "# Generated by Geltdro Mock Script - $(Get-Date -Format 'dd/MM/yyyy HH:mm:ss')`n"
        $Body = $Inventory | ForEach-Object { Get-SSHHostBlock $_ }

        # Asegurar directorio (Liskov/System integrity)
        $TargetDir = Split-Path $ConfigPath
        if (!(Test-Path $TargetDir)) { New-Item -ItemType Directory -Path $TargetDir -Force }

        # Escritura atómica
        $Header + $Body | Out-File -FilePath $ConfigPath -Encoding utf8 -Force

        Write-Host "Done. Config ready at $ConfigPath" -ForegroundColor Green
    }
    catch {
        Write-Error "System Failure: $($_.Exception.Message)"
    }
}

Update-SSHConfig
