services:
  server:
    image: stalwartlabs/stalwart:v0.15.5
    container_name: stalwart
    restart: unless-stopped
    volumes:
      - data:/opt/stalwart
    environment:
      - TZ=America/Bogota
      - SSL_CERT_FILE=/step_ca/certs/root_ca.crt
    networks:
      network_service:
        ipv4_address: 10.10.3.35
      
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stalwart.rule=Host(`mail.docker.local`)"
      - "traefik.http.routers.stalwart.entrypoints=websecure"
      - "traefik.http.routers.stalwart.tls=true"
      - "traefik.http.services.stalwart.loadbalancer.server.port=8080"

volumes:
  data:
    external: false
  step-ca_data:
    external: true

networks:
  network_service:
    external: true