services:
  mattermost:
    image: mattermost/mattermost-team-edition:10.11.8
    container_name: mattermost
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      network_service:
        ipv4_address: 10.10.3.120
    tmpfs:
      - /tmp
    volumes:
      - config:/mattermost/config:rw
      - data:/mattermost/data:rw
      - logs:/mattermost/logs:rw
      - plugins:/mattermost/plugins:rw
      - client_plugins:/mattermost/client/plugins:rw
      - bleve_indexes:/mattermost/bleve-indexes:rw
      - step-ca_data:/step_ca:ro
    environment:
      - TZ=America/Bogota
      - MM_SQLSETTINGS_DRIVERNAME=postgres
      - MM_SQLSETTINGS_DATASOURCE=postgres://postgres_shared:postgres_shared@10.10.3.153:5432/mattermost?sslmode=disable&connect_timeout=10
      - MM_BLEVESETTINGS_INDEXDIR=/mattermost/bleve-indexes
      - SSL_CERT_FILE=/step_ca/certs/root_ca.crt
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`chat.docker.local`)"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.routers.mattermost.tls=true"
      - "traefik.http.services.mattermost.loadbalancer.server.port=8065"
      - "traefik.http.routers.woodpecker-secure.tls.certresolver=step-ca-resolver"

networks:
  network_service:
    external: true

volumes:
  config:
  data:
  logs:
  plugins:
  client_plugins:
  bleve_indexes:
  step-ca_data:
        external: true