dhcp-range=set:relay_net,192.168.1.2,192.168.1.100,255.255.255.0,24h

dhcp-option=tag:relay_net,option:router,192.168.1.1
dhcp-option=tag:relay_net,option:dns-server,10.10.3.200

no-dhcp-interface=eth0
no-dhcp-interface=eth1
no-dhcp-interface=eth2