services:
  traefik:
    image: "traefik:v3.4"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      network_service:
        ipv4_address: 10.10.3.199
    environment:
      - LEGO_CA_CERTIFICATES=/etc/ssl/step-ca/certs/root_ca.crt
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - step-ca_data:/etc/ssl/step-ca:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.docker.local`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"

volumes:
  step-ca_data:
    external: true

networks:
  network_service:
    external: true