services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    restart: always
    ports:
      - "8001:8000"
    networks:
      network_service:
        ipv4_address: 10.10.3.22
    environment:
      - WOODPECKER_OPEN=true
      - WOODPECKER_ADMIN=admin
      - WOODPECKER_AGENT_SECRET=supersecret123
      
  
      - WOODPECKER_HOST=http://10.10.3.22:8001
      
      - WOODPECKER_GITEA=true
      - WOODPECKER_GITEA_URL=http://IP_DE_TU_GITEA:3000
      - WOODPECKER_GITEA_CLIENT=tu_client_id_generado_en_gitea
      - WOODPECKER_GITEA_SECRET=tu_client_secret_generado_en_gitea

      - WOODPECKER_GRPC_ADDR=0.0.0.0:9000
      - WOODPECKER_SERVER_ADDR=0.0.0.0:8000
      - WOODPECKER_DATABASE_DRIVER=sqlite3
      - WOODPECKER_DATABASE_DATASOURCE=/var/lib/woodpecker/woodpecker.sqlite3
    volumes:
      - data:/var/lib/woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    restart: always
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WOODPECKER_SERVER=10.10.3.22:9000
      - WOODPECKER_AGENT_SECRET=supersecret123
      - WOODPECKER_MAX_WORKFLOWS=2
    networks:
      network_service:
        ipv4_address: 10.10.3.23

volumes:
  data:

networks:
  network_service:
    external: true