services:
  mongo_shared:
    image: mongo:8.0
    container_name: mongo_shared
    restart: unless-stopped
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'shared'
      MONGO_INITDB_ROOT_PASSWORD: 'shared'

    networks:
      network_service:
        ipv4_address: 10.10.3.20 #27017

volumes:
  data:
    external: false

networks:
  network_service:
    external: true