services:
  # Restart compose orchestrator
  ubuntu:
    image: ubuntu:local
    container_name: ubuntu-maint
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
      args:
        docker_app: true
        app_essentials: true

  ubuntu-nd:
    image: ubuntu:local-nd
    container_name: ubuntu-nd-maint
    build:
      context: .
      dockerfile: Dockerfile
      args:
        docker_app: false
        app_essentials: false
