services:
  mcp-cookery:
    image: crystaldba/postgres-mcp:0.3.0
    container_name: mcp-postgres-cookery
    environment:
      - DATABASE_URI=postgresql://postgres_xaiena:postgres_xaiena@10.10.3.154:5432/cookery
    command: 
      - "--access-mode=unrestricted"
      - "--transport=sse"
    restart: unless-stopped
    networks:
      - network_service
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mcp-cookery.rule=Host(`mcp-cookery.docker.local`)"
      - "traefik.http.routers.mcp-cookery.entrypoints=websecure"
      - "traefik.http.routers.mcp-cookery.tls=true"
      - "traefik.http.services.mcp-cookery.loadbalancer.server.port=8000"

networks:
  network_service:
    external: true