services:
  maintainer:
    image: maintainer:local
    container_name: maintainer
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data:/home/${USERNAME}
      - etc:/etc
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt:/mnt # disk mount from host
      - shared:/home/shared
      - $SSH_AUTH_SOCK:/ssh-agent
    networks:
      network_user:
        ipv4_address: 10.10.4.18
    group_add:
      - "998"

networks:
  network_user:
    external: true

volumes:
  data:
    external: false
  etc:
    external: false
  shared:
    external: false